- name: "backlog"
  color: "7ef7ef"
- name: "bug"
  color: "d73a4a"
- name: "chore"
  color: "ffffff"
- name: "ci"
  color: "0075ca"
- name: "dependencies"
  color: "276bd1"
- name: "documentation"
  color: "0075ca"
- name: "duplicate"
  color: "cfd3d7"
- name: "feature request"
  color: "fcf95a"
- name: "good first issue"
  color: "7057ff"
- name: "help wanted"
  color: "008672"
- name: "invalid"
  color: "e4e669"
- name: "need repro"
  color: "c66037"
- name: "performance"
  color: "80c042"
- name: "priority:critical"
  color: "b60205"
- name: "priority:high"
  color: "d93f0b"
- name: "priority:medium"
  color: "fbca04"
- name: "priority:low"
  color: "0e8a16"
- name: "refactor"
  color: "1d637f"
- name: "regression"
  color: "ea8785"
- name: "tests"
  color: "f06dff"
- name: "wontfix"
  color: "ffffff"
- name: "frontend"
  color: "ff0000"
- name: "backend"
  color: "00ff00"
- name: "infrastructure"
  color: "0000ff"
- name: "video"
  color: "ff00ff"
