imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
group_imports = "StdExternalCrate"
wrap_comments = true
style_edition = "2021"
format_macro_matchers = true
hard_tabs = true
reorder_impl_items = true
max_width = 125