name: Bug Report
description: Found bugs? Share them here
title: "A brief description of the bug"
labels: ["bug"]
assignees:
  - ScuffleTV/reviewers
body:
  - type: markdown
    attributes:
      value: |
        ### **Thank you for taking the time to fill out this Bug Report!**
        Please provide as much information as possible. This will help us resolve the Bug quickly and accurately.
        If you know which application this bug is for, please add the appropriate label to this issue.
  - type: markdown
    attributes:
      value: ---
  - type: textarea
    id: what-happened
    attributes:
      label: What seems to be the problem?
      description: |
        A clear and concise description of what needs to be fixed.
        *Make sure there are no misunderstandings here. It would be best if you have a video/screenshot for us.*
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What is the affected environment?
      options:
        - "Microsoft Windows"
        - "Apple macOS"
        - "Linux"
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: On what browser did you see the problem?
      options:
        - "Chromium (Google Chrome, Microsoft Edge, Brave, Vivaldi, etc.)"
        - "Mozilla Firefox"
        - "Opera (GX)"
        - "Apple Safari"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How do we replicate that?
      description: |
        This includes the steps for reproducing the problem, the expected result, and the actual result.
      placeholder: |
        1. ..
        2. ..
        3. ..
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
