<script lang="ts">
	import Fa from "svelte-fa";
	import {
		faAirbnb,
		faAmazon,
		faAppStore,
		faBandcamp,
		faBehance,
		faCodepen,
		faDeezer,
		faDev,
		faDeviantart,
		faDiscord,
		faDropbox,
		faEbay,
		faEtsy,
		faFacebook,
		faFlickr,
		faFreeCodeCamp,
		faGithub,
		faGitlab,
		faGoodreads,
		faGooglePlay,
		faHackerNews,
		faInstagram,
		faItchIo,
		faItunes,
		faJsfiddle,
		faKickstarter,
		faLastfm,
		faLine,
		faLinkedin,
		faMedium,
		faNpm,
		faOdysee,
		faPatreon,
		faPaypal,
		faPinterest,
		faProductHunt,
		faQuora,
		faRedditAlien,
		faRenren,
		faSkype,
		faSnapchat,
		faSoundcloud,
		faSpotify,
		faStackOverflow,
		faSteam,
		faTelegram,
		faThreads,
		faTiktok,
		faTumblr,
		faTwitch,
		faTwitter,
		faUnsplash,
		faVimeo,
		faVk,
		faWhatsapp,
		faWikipediaW,
		faXing,
		faXTwitter,
		faYoutube,
		faZhihu,
		type IconDefinition,
	} from "@fortawesome/free-brands-svg-icons";
	import { faGlobe } from "@fortawesome/free-solid-svg-icons";

	export let url: string;

	const icons: { [key: string]: IconDefinition } = {
		"airbnb.com": faAirbnb,
		"amazon.com": faAmazon,
		"apps.apple.com": faAppStore,
		"bandcamp.com": faBandcamp,
		"behance.net": faBehance,
		"codepen.io": faCodepen,
		"deezer.com": faDeezer,
		"dev.to": faDev,
		"deviantart.com": faDeviantart,
		"discord.com": faDiscord,
		"discord.gg": faDiscord,
		"dropbox.com": faDropbox,
		"ebay.com": faEbay,
		"etsy.com": faEtsy,
		"facebook.com": faFacebook,
		"flickr.com": faFlickr,
		"freecodecamp.org": faFreeCodeCamp,
		"github.com": faGithub,
		"gitlab.com": faGitlab,
		"goodreads.com": faGoodreads,
		"play.google.com": faGooglePlay,
		"news.ycombinator.com": faHackerNews,
		"instagram.com": faInstagram,
		"itch.io": faItchIo,
		"itunes.apple.com": faItunes,
		"jsfiddle.net": faJsfiddle,
		"kickstarter.com": faKickstarter,
		"last.fm": faLastfm,
		"linkedin.com": faLinkedin,
		"line.me": faLine,
		"medium.com": faMedium,
		"npmjs.com": faNpm,
		"odysee.com": faOdysee,
		"patreon.com": faPatreon,
		"paypal.me": faPaypal,
		"pinterest.com": faPinterest,
		"producthunt.com": faProductHunt,
		"quora.com": faQuora,
		"reddit.com": faRedditAlien,
		"renren.com": faRenren,
		"skype.com": faSkype,
		"snapchat.com": faSnapchat,
		"soundcloud.com": faSoundcloud,
		"stackoverflow.com": faStackOverflow,
		"spotify.com": faSpotify,
		"steamcommunity.com": faSteam,
		"t.co": faTwitter,
		"t.me": faTelegram,
		"telegram.me": faTelegram,
		"threads.net": faThreads,
		"tiktok.com": faTiktok,
		"tumblr.com": faTumblr,
		"twitch.tv": faTwitch,
		"twitter.com": faTwitter,
		"unsplash.com": faUnsplash,
		"vimeo.com": faVimeo,
		"vk.com": faVk,
		"wa.me": faWhatsapp,
		"wikipedia.org": faWikipediaW,
		"x.com": faXTwitter,
		"youtube.com": faYoutube,
		"youtu.be": faYoutube,
		"xing.com": faXing,
		"zhihu.com": faZhihu,
	};

	function urlToIcon(url: string): IconDefinition {
		try {
			const urlObj = new URL(url);
			for (const [domain, icon] of Object.entries(icons)) {
				if (urlObj.hostname.endsWith(domain)) {
					return icon;
				}
			}
			return faGlobe;
		} catch (e) {
			return faGlobe;
		}
	}

	$: icon = urlToIcon(url);
</script>

<Fa {icon} fw />
