[package]
name = "video-player-types"
version = "0.0.1"
edition = "2021"
license = "BSL-1.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ulid = { version = "1.1", default-features = false }
url = { version = "2.5", default-features = false, features = ["serde"] }
